# Site settings
title: Hardik Patel
description: "Thoughts on Computer Science and Finance"
tagline: ""
baseurl: ""
url: "https://hardikp.github.io"
twitter_username: hardikp
github_username:  hardikp

twitter:
  username: hardikp
social:
  name: Hardik Patel
  links:
    - https://twitter.com/hardikp
    - https://www.facebook.com/hardikp0
    - https://www.linkedin.com/in/hardikp12
    - https://plus.google.com/+HardikPatel1
    - https://github.com/hardikp
    - https://keybase.io/hardikp
    - https://medium.com/@hardikp
    - https://www.instagram.com/hardikp

# Build settings
markdown: kramdown
permalink: pretty

# Plugins:
gems:
  - jekyll-paginate
  - jekyll-seo-tag

# Pagination configuration
paginate: 5
paginate_path: "page:num"

# About/contact
author:
  name: Hardik Patel
  url: http://www.hardikp.com
  email: hardikp12@gmail.com
