# Site settings
title: Hardik Patel
description: "Thoughts on Computer Science and Finance"
tagline: ""
baseurl: ""
url: "http://hardikp.github.io"
twitter_username: hardikp
github_username:  hardikp

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# About/contact
author:
  name: Hardik Patel
  url: http://www.hardikp.com
  email: hardikp12@gmail.com
