# Site settings
title: Hardik Patel
description: "Thoughts on Machine Learning and Computer Science"
tagline: ""
baseurl: ""
url: "https://www.hardikp.com"
twitter_username: hardikp
github_username:  hardikp

twitter:
  username: hardikp
social:
  name: Hardik Patel
  links:
    - https://twitter.com/hardikp
    - https://www.facebook.com/hardikp0
    - https://www.linkedin.com/in/hardikp12
    - https://plus.google.com/+HardikPatel1
    - https://github.com/hardikp
    - https://keybase.io/hardikp
    - https://medium.com/@hardikp
    - https://www.instagram.com/hardikp
    - https://gitlab.com/hardikp
    - https://www.quora.com/profile/Hardik-Patel-8
    - https://angel.co/hardikp
    - https://21.co/hardikp
    - https://slides.com/hardikp

# Build settings
markdown: kramdown
permalink: pretty

# Plugins:
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Pagination configuration
paginate: 10
# paginate_path: "/blog/page:num/"

future: true

# About/contact
author:
  name: Hardik Patel
  url: http://www.hardikp.com
  email: hardikp12@gmail.com
